### PR TITLE
fix(secrets): remove default events from update action

### PR DESCRIPTION
**Pull request by JordanSussman**
closes https://github.com/go-vela/community/issues/178

### CODE REVIEW

**Review by wass3r — APPROVED** [review]

**Comment by davidvader** [comment]
are we sure that this does not cause an inverse bug, where updates now default to NO events?

via 
https://github.com/go-vela/cli/blob/master/action/secret/update.go#L61

**Comment by wass3r** [comment]
Good callout - sorry i missed that :cone_of_shame:

**Comment by JordanSussman** [comment]
These changes are working as intended since the [UpdateSecret](https://github.com/go-vela/server/blob/db01ce5562a4f631e10a8e08b824dd138c7a9c0f/api/secret.go#L440-L442) logic on the Server validates if events are set in the payload before deciding if that field should be updated in the database. I've successfully validated this locally but happy for others to provide another set of validation.

**Comment by davidvader** [comment]
> These changes are working as intended since the [UpdateSecret](https://github.com/go-vela/server/blob/db01ce5562a4f631e10a8e08b824dd138c7a9c0f/api/secret.go#L440-L442) logic on the Server validates if events are set in the payload before deciding if that field should be updated in the database. I've successfully validated this locally but happy for others to provide another set of validation.

> Or optionally provide the events in the PUT when none are provided.

👍  sounds good. 
Just wanted to make sure that the [`GetEvents`](https://github.com/go-vela/types/blob/master/library/secret.go#L211) on the library.secret used to do the PUT wouldn't return `[]`  when none are provided. For example `images` which when provided an empty slice actually do wipe out the enabled images.. thanks for validating!

**Review by davidvader — APPROVED** [review]

**Comment by JordanSussman** [comment]
Adding some local output to showcase that the updated code works against a Vela 0.6.2 server:

```sh
$ ./release/darwin/amd64/vela add secret --org JordanSussman --repo apm-test --name test --value star --event push --event pull_request
{
	AllowCommand: true,
	Events: [push pull_request],
	ID: 37,
	Images: [],
	Name: test,
	Org: JordanSussman,
	Repo: apm-test,
	Team: ,
	Type: repo,
	Value: [secure],
}

$ ./release/darwin/amd64/vela update secret --org JordanSussman --repo apm-test --name test --value bar
{
	AllowCommand: true,
	Events: [push pull_request],
	ID: 37,
	Images: [],
	Name: test,
	Org: JordanSussman,
	Repo: apm-test,
	Team: ,
	Type: repo,
	Value: [secure],
}
```

**Review by jbrockopp — APPROVED** [review]
LGTM

**Pull request merged**
